version: '3.7'
services:
    discord-2000:
        container_name: 'discord-2000'
        user: node

        build:
            context: .
            dockerfile: Dockerfile
            args:
                - token=${token}
                - cmdPrefix=${cmdPrefix}
                - presence_text_channel_updates=${presence_text_channel_updates}
                - enable_presence_updates=${enable_presence_updates}
                - timezone=${timezone}
                - NODE_ENV=production

        network_mode: host

        volumes:
            - .:/app
            - /app/node_modules

        environment:
            - token=${token}
            - cmdPrefix=${cmdPrefix}
            - presence_text_channel_updates=${presence_text_channel_updates}
            - enable_presence_updates=${enable_presence_updates}
            - timezone=${timezone}
            - NODE_ENV=production

        depends_on:
            - 'database'

        restart: always
        command: npm run start

    database:
        image: mariadb:10.5.8
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${mysql_root_password}
            - MYSQL_DATABASE=${mysql_database}
            - MYSQL_USER=${mysql_user}
            - MYSQL_PASSWORD=${mysql_password}
            - MYSQL_ALLOW_EMPTY_PASSWORD=false
        volumes:
            - .mysql-data:/var/lib/mysql
