version: '3.7'
services:
    discord-2000:
        container_name: 'discord-2000'
        user: node

        build:
            context: .
            dockerfile: Dockerfile
            args:
                - TOKEN=${TOKEN}
                - CMD_PREFIX=${CMD_PREFIX}
                - TIMEZONE=${TIMEZONE}
                - NODE_ENV=production
        networks:
            - nasdc-private-net
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - TOKEN=${TOKEN}
            - CMD_PREFIX=${CMD_PREFIX}
            - TIMEZONE=${TIMEZONE}
            - NODE_ENV=production

        restart: always
        command: bash -c "npm run start"

networks:
    nasdc-private-net:
        external: true
