version: '3.7'
services:
  discord-2000:
    container_name: "discord-2000"

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - token=${token}
        - cmdPrefix=${cmdPrefix}
        - NODE_ENV=production

    network_mode: host

    volumes:
      - .:/app:cached,Z
  
    environment:
      - token=${token}
      - cmdPrefix=${cmdPrefix}
      - NODE_ENV=production
  
    restart: always

volumes:
  discord-2000: